FC := gfortran


SRC = $(wildcard *.f90)
OBJ = $(SRC:.f90=.o)

all:myprogram

# COMPILE
%.o : %.F90
	@echo "===== compiling $@ (newer: $?)"
	$(FC) -c $< 

# MODULE (fake)
%.mod : %.o
	@echo "===== faking module $@ (newer: $?)"
	@:

# LINK
myprogram: $(OBJ)
	@echo "===== linking $@ (newer: $?)"
	$(FC) -o myprogram $^

.PHONY:clean all test

clean:
	rm -f *.mod *.o myprogram

.SUFFIXES:
Makefile: ;

%.f90 : ;
%.F90 : ;

%.d : ;

include test.mk

include dependencies/*.d
